services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    command: sh -c "cron && /auction"
    networks:
      - localNetwork
    container_name: app
    depends_on:
      - mongodb  # Garante que o MongoDB seja iniciado primeiro
    restart: always  # Reinicia automaticamente em caso de falhas

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge
