POST http://localhost:8080/auction
Host: localhost:8080
Content-Type: application/json

{
    "product_name": "teste2",
    "category": "teste2",
    "description": "teste do lucas2",
    "condition": 1
}

#######
GET http://localhost:8080/auction/db7ce80e-c652-43c2-b998-20a635535acd
Host: localhost:8080
Content-Type: application/json

######
GET http://localhost:8080/auction?status=0
Host: localhost:8080
Content-Type: application/json

######
GET http://localhost:8080/auction/winner/db7ce80e-c652-43c2-b998-20a635535acd
Host: localhost:8080
Content-Type: application/json

#####
GET http://localhost:8080/auctions/expired
Host: localhost:8080
Content-Type: application/json


#####
GET http://localhost:8080/auctions/closeexpiredauctions
Host: localhost:8080
Content-Type: application/json

