POST http://localhost:8080/bid
Host: localhost:8080
Content-Type: application/json

{
    "user_id": "8afc6593-e09b-4acb-9c7a-eb3cd094e95b",
    "auction_id": "56357819-8005-4e82-abf9-6bb393c41e79",
    "amount": 7000,
    "causes": "teste"
}

#######

GET http://localhost:8080/bid
Host: localhost:8080
Content-Type: application/json

